# Generated by Django 4.0.3 on 2022-03-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_customuser_amory_streak_customuser_amory_lastlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Harrison_lastLogin',
            field=models.DateField(default=(0, 0, 0)),
        ),
    ]
