# Generated by Django 4.0.3 on 2022-03-23 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_alter_customuser_amory_lastlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Amory_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437846)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Business_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437922)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Cornwall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437952)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Forum_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437885)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Geoffrey_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438006)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='GreatHall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438033)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Harrison_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437632)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Hatherly_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438066)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Health_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438566)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Henry_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438098)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Iais_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438152)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Innovation_One_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438125)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Laver_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438205)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438236)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Living_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438263)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mary_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438289)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mood_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438488)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Northcott_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 437979)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Old_Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438324)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Peter_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438351)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Physics_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438381)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Queen_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438407)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Reed_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438434)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Sports_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438514)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Streatham_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438540)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Washington_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438593)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Wellbeing_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438460)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Xfi_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438624)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='into_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 13, 35, 53, 438179)),
        ),
    ]
