# Generated by Django 4.0.3 on 2022-03-23 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_customuser_amory_lastlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Amory_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878227)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Business_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878321)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Cornwall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878355)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Forum_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878279)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Geoffrey_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878417)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='GreatHall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878453)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Harrison_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878115)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Hatherly_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878489)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Health_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879098)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Henry_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878523)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Iais_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878593)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Innovation_One_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878562)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Laver_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878658)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878694)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Living_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878727)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mary_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878757)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mood_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879001)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Northcott_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878386)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Old_Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878791)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Peter_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878827)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Physics_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878866)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Queen_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878902)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Reed_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878932)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Sports_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879032)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Streatham_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879063)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Washington_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879129)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Wellbeing_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878963)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Xfi_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 879158)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='into_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 5, 52, 878623)),
        ),
    ]
