# Generated by Django 4.0.3 on 2022-03-23 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_customuser_userrewards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Amory_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 676960)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Business_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677052)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Cornwall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677085)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Forum_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677011)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Geoffrey_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677147)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='GreatHall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677179)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Harrison_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 676724)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Hatherly_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677215)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Health_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677828)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Henry_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677254)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Iais_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677324)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Innovation_One_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677293)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Laver_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677390)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677426)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Living_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677457)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mary_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677487)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mood_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677731)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Northcott_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677116)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Old_Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677523)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Peter_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677558)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Physics_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677592)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Queen_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677632)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Reed_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677662)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Sports_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677763)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Streatham_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677793)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Washington_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677859)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Wellbeing_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677693)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Xfi_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677889)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='into_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 14, 33, 57, 677355)),
        ),
    ]
