# Generated by Django 4.0.1 on 2022-03-23 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0012_alter_customuser_amory_lastlogin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='Amory_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951463)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Business_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951566)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Cornwall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951589)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Forum_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951486)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Geoffrey_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951625)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='GreatHall_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951644)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Harrison_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951425)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Hatherly_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951663)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Health_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 952029)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Henry_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951707)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Iais_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951762)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Innovation_One_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951741)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Laver_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951795)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951814)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Living_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951831)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mary_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951848)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Mood_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951974)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Northcott_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951608)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Old_Library_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951869)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Peter_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951887)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Physics_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951905)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Queen_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951924)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Reed_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951941)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Sports_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951993)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Streatham_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 952010)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Washington_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 952045)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Wellbeing_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951957)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='Xfi_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 952065)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='into_lastLogin',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 23, 6, 16, 951779)),
        ),
    ]
