# Generated by Django 4.0.1 on 2022-03-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenGame', '0002_buildingoftheday_reward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingoftheday',
            old_name='buidling_desc',
            new_name='building_desc',
        ),
    ]
