# Generated by Django 4.0.1 on 2022-03-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenGame', '0003_rename_buidling_desc_buildingoftheday_building_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingoftheday',
            name='building_desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='buildingoftheday',
            name='reward',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
