# Generated by Django 4.0.1 on 2022-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenGame', '0004_alter_buildingoftheday_building_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportToAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=200)),
                ('problem_description', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='buildingoftheday',
            old_name='building_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buildingoftheday',
            name='building_desc',
        ),
        migrations.AddField(
            model_name='buildingoftheday',
            name='description',
            field=models.CharField(default='N/A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingoftheday',
            name='reward',
            field=models.CharField(max_length=200),
        ),
    ]
